### PR TITLE
Create CLI Password Generator

### PR DESCRIPTION
**Pull request by ayushete02**
CLI python program to generate strong passwords based on user preferences.

### CODE REVIEW

**Comment by ambushneupane** [comment]
@ayushete02  Delete the pyache file .

**Comment by ayushete02** [comment]
@ambushneupane Done

**Comment by ayushete02** [comment]
I think now here is now issue in file so you can merge it

**Comment by ambushneupane** [comment]
@ayushete02 Done! and Nice Work.

**Pull request merged**
